//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// TxtFuncBookmark.rc で使用
//
#define IDOPEN                          3
#define IDI_APP                         100
#define IDR_MENU_POPUP_TAG              101
#define IDR_MENU_POPUP_BOOK             102
#define IDR_MENU_POPUP_SUBTITLE         103
#define IDD_BOOK                        106
#define IDD_LINK                        107
#define IDD_FILESEARCH                  109
#define IDD_RUBY                        113
#define IDD_SEARCH                      114
#define IDD_COVERINFO                   115
#define IDD_BOOK2                       116
#define IDC_EDIT_TAG                    1000
#define IDC_EDIT_TITLE                  1001
#define IDC_EDIT_URL                    1002
#define IDC_STATIC_IMG                  1003
#define IDC_EDIT_AUTHOR                 1004
#define IDC_BUTTON_GETINFO              1005
#define IDC_BUTTON_IMAGE                1006
#define IDC_BUTTON_URL                  1007
#define IDC_LINK_LIST                   1008
#define IDC_BUTTON_SP                   1008
#define IDC_STATIC_SPBAR                1009
#define IDC_BUTTON_LATEST               1010
#define IDC_BUTTON_READ                 1011
#define IDC_BUTTON_SIORI                1012
#define IDC_EDIT_NUM                    1013
#define IDC_SEARCH_TEXT                 1014
#define IDC_SEARCH_FILE                 1015
#define IDC_USE_REGEXP                  1016
#define IDC_SEARCH_PATH                 1017
#define IDC_LIST_RUBY                   1020
#define IDC_EDIT_FILTER                 1021
#define IDC_COMBO1                      1024
#define IDC_COMBO_FOLDER                1024
#define IDD_TAG                         28444
#define IDD_BOOKLIST                    40000
#define IDS_BMH_TITLE                   40001
#define IDS_BMH_URL                     40002
#define IDS_BMH_AUTHOR                  40003
#define IDS_BMH_READCNT                 40004
#define IDS_BMH_TOTAL                   40005
#define IDS_BMH_VISIT_DATE              40006
#define IDS_BMH_READPAGE                40007
#define IDS_BMH_TOTALPAGE               40008
#define IDS_DELETE_TAG                  40009
#define IDS_DELETE_TAG_MULTI            40010
#define IDS_DELETE_BOOK                 40011
#define IDS_DELETE_BOOK_MULTI           40012
#define IDS_IMAGE_NOSUPPORT             40013
#define IDS_COVERFILE                   40014
#define IDM_TAG_ADD                     40015
#define IDM_TAG_MODIFY                  40016
#define IDM_TAG_DELETE                  40017
#define IDM_TAG_UP                      40018
#define IDM_TAG_DOWN                    40019
#define IDM_UPDATECHECK                 40020
#define IDM_UPDATECHECKALL              40021
#define IDM_BOOK_OPEN                   40022
#define IDM_BOOK_ADD                    40023
#define IDM_BOOK_MODIFY                 40024
#define IDM_BOOK_DELETE                 40025
#define IDM_BOOK_UP                     40026
#define IDM_BOOK_DOWN                   40027
#define IDM_SUBTITLE_OPEN               40028
#define IDM_CANCEL                      40029
#define IDS_TIPS_TAG_ADD                40030
#define IDS_TIPS_TAG_MODIFY             40031
#define IDS_TIPS_TAG_DELETE             40032
#define IDS_TIPS_TAG_UP                 40033
#define IDS_TIPS_TAG_DOWN               40034
#define IDS_TIPS_BOOK_OPEN              40035
#define IDS_TIPS_BOOK_ADD               40036
#define IDS_TIPS_BOOK_MODIFY            40037
#define IDS_TIPS_BOOK_DELETE            40038
#define IDS_TIPS_BOOK_UPDATE            40039
#define IDS_TIPS_BOOK_UPDATE_ALL        40040
#define IDS_TIPS_BOOK_UP                40041
#define IDS_TIPS_BOOK_DOWN              40042
#define IDS_TIPS_SUBTITLE_OPEN          40043
#define IDS_ERROR_FOLDER                40044
#define IDS_ERROR_BOOK                  40045
#define IDM_PROPERTY                    40046
#define IDM_FOLDER_OPEN                 40047
#define IDS_URLFILE                     40048
#define IDM_SUBTITLE_READ               40049
#define IDM_SUBTITLE_NOREAD             40050
#define IDS_ERROR_SUBTITLE              40051
#define IDS_LIST_PAGE                   40052
#define IDS_TOPPAGE                     40053
#define IDS_IDGOTOPAGE                  40054
#define IDS_IDADDBOOKMARK               40055
#define IDS_IDDELBOOKMARK               40056
#define IDS_IDLINKSTAY                  40057
#define IDS_IDBOOKMARK                  40058
#define IDS_IDSUBTITLE                  40059
#define IDS_TITLE_PAGE_NAME             40060
#define IDM_STAYONTOP                   40061
#define IDS_TAG_FAVORITE                40062
#define IDS_TITLE_SIORI                 40063
#define IDS_TITLE_LATEST                40064
#define IDS_TITLE_VISIT                 40065
#define IDS_DELETE_SIORI                40066
#define IDS_BMH_SEARCH_RESULT           40067
#define IDC_ABORT                       40068
#define IDS_FILESEARCH_TITLE            40069
#define IDS_FILESEARCH_RUNNING          40070
#define IDS_TITLE_TEXT                  40071
#define IDS_TITLE_RUBY                  40072
#define IDC_COMBO_SEARCH                40073
#define IDPREVSEARCH                    40074
#define IDC_CHECK_LOOP                  40075
#define IDS_SEARCH_NOT_FOUND            40076
#define IDS_TITLE_AUTOSCROLL            40077
#define IDS_FILTER_TEXT                 40078
#define IDS_ERROR_MAKECACHE             40079
#define ID_MAKECACHE                    40080
#define IDM_MAKECACHE                   40081
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40082
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
